name: com.vms.PlanksAndBeams
main: com.vistamaresoft.pnb.PlanksAndBeams
version: 0.5.3
author: Maurizio M. Gavioli aka Miwarre
team: VistaMare Software
description: "To provide players with non-standard planks and beams."
license: Creative Common by-sa
website: http://www.vistamaresoft.com
